services:
  front:
    container_name: ESGI-pa-front
    image: ghcr.io/louis-guidez/esgi-pa-front
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - MERCURE_BASE_URL=${MERCURE_BASE_URL}
      - NUXT_PUBLIC_STRIPE_KEY=${STRIPE_KEY}
      - GEOAPIFY_API_KEY=${GEOAPIFY_API_KEY}
      - NODEMAILER_HOST=${NODEMAILER_HOST}
      - NODEMAILER_PORT=${NODEMAILER_PORT}
      - NODEMAILER_SECURE=${NODEMAILER_SECURE}
      - NODEMAILER_USER=${NODEMAILER_USER}
      - NODEMAILER_PASS=${NODEMAILER_PASS}
    restart: always

