services:
  front:
    container_name: ESGI-pa-front
    image: ghcr.io/louis-guidez/esgi-pa-front
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - STRIPE_KEY=${STRIPE_KEY}
      - GEOAPIFY_API_KEY=${GEOAPIFY_API_KEY}
    restart: always

