services:
  front:
    container_name: ESGI-pa-front
    # image: ghcr.io/louis-guidez/esgi-pa-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_BASE_URL=${NUXT_PUBLIC_API_BASE_URL}
      - NUXT_PUBLIC_MERCURE_BASE_URL=${NUXT_PUBLIC_MERCURE_BASE_URL}
      - NUXT_PUBLIC_STRIPE_KEY=${NUXT_PUBLIC_STRIPE_KEY}
      - NUXT_PUBLIC_GEOAPIFY_API_KEY=${NUXT_PUBLIC_GEOAPIFY_API_KEY}
      - NUXT_NODEMAILER_HOST=${NUXT_NODEMAILER_HOST}
      - NUXT_NODEMAILER_PORT=${NUXT_NODEMAILER_PORT}
      - NUXT_NODEMAILER_SECURE=${NUXT_NODEMAILER_SECURE}
      - NUXT_NODEMAILER_AUTH_USER=${NUXT_NODEMAILER_USER}
      - NUXT_NODEMAILER_AUTH_PASS=${NUXT_NODEMAILER_PASS}
    restart: always

